* Helm chart for Greenbone Vulnerability Management (GVM)
** Introduction
You can use the provided helm chart in this repository to deploy
Greenbone Source Edition (GSE) on your kubernetes cloud.

** Getting Helm
To use "helm" you have to first install it! For more information about
installing helm follow the instructions at [[https://github.com/helm/helm#install][helm installation notes]].

** Building chart from source
Use the following instructions to build the gvm helm chart from
source:

#+NAME: build helm chart for gvm
#+BEGIN_SRC shell
git clone https://github.com/admirito/gvm-containers.git

cd gvm-containers/chart

helm dependency build gvm
helm package gvm
#+END_SRC

This should leave you with a =gvm-*.tgz= file ready to be deployed in
the k8s.

** Installing GVM via helm chart
GVM uses several components and databases that should be deployed on
k8s. Therefore, to have better control on you installation it is
recommended to crate a separate namespace for it:

#+NAME: create a namespace for GVM installation
#+BEGIN_SRC shell
kubectl create namespace gvm
#+END_SRC

Then you can install the chart with helm:

#+NAME: install GVM helm chart
#+BEGIN_SRC shell
helm install gvm ./gvm-*.tgz --namespace gvm --timeout 20m --set gvmd-db.postgresqlPassword="mypassword"
#+END_SRC

You have to also provide =persistence= configuration, to make sure your
data persist in pods life cycle.

** Configuration
The following table lists some of the useful configurable parameters
of the GVM chart and their default values. For a complete list see
[[./gvm/values.yaml][values.yaml]] file.

| Parameter                                      | Description                                                  | Default |
|------------------------------------------------+--------------------------------------------------------------+---------|
| image.gvmd.tag                                 | the docker tag for gvmd image                                | 20      |
| image.gsad.tag                                 | the docker tag for gsad image                                | 20      |
| image.openvas.tag                              | the docker tag for openvas image                             | 20      |
| gvmd-db.image.tag                              | the docker tag for gvm-postgres image                        | 20      |
| syncFeedsAfterInstall                          | sync all the GVM feeds with post-install hooks               | true    |
| persistence.existingClaim                      | name of an existing pvc for data (nvt/scap/cert) persistence | ""      |
| gvmd-db.postgresqlPassword                     | the password for "gvmduser" in "gvmd" postgresql database    | ""      |
| gvmd-db.persistence.existingClaim              | name of an existing pvc for postgresql data persistence      | ""      |
| openvas-redis.master.persistence.existingClaim | name of an existing pvc for redis data persistence           | ""      |
