version: '2.1'

volumes:
  gvm-var-lib: {}
  run-gvm: {}

services:
  gvmd-data-sync:
    image: ${GVMD_IMAGE_NAME:-admirito/gvmd}:${GVMD_IMAGE_TAG:-latest}
    volumes:
      - gvm-var-lib:/var/lib/gvm
      - run-gvm:/run/gvm
    command:
      - sh
      - -xc
      - |
        chown -R gvm:gvm /var/lib/gvm
        greenbone-feed-sync -vvv --type gvmd-data
    # environment:
    #   GREENBONE_FEED_SYNC_GVMD_DATA_URL: "rsync://feed.community.greenbone.net/community/data-feed/22.04/"
