version: '2.1'

volumes:
  openvas-var-lib: {}
  run-gvm: {}

services:
  nvt-sync:
    image: ${GVMD_IMAGE_NAME:-admirito/gvmd}:${GVMD_IMAGE_TAG:-latest}
    volumes:
      - openvas-var-lib:/var/lib/openvas
      - run-gvm:/run/gvm
    command:
      - sh
      - -xc
      - |
        chown -R gvm:gvm /var/lib/openvas
        greenbone-feed-sync -vvv --type nasl
    # environment:
    #   GREENBONE_FEED_SYNC_NASL_URL: "rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/vt-data/nasl/"
