* gvm-containers
** Introduction
This is the Git repo of the tools to deploy Greenbone Vulnerability
Management with containers. It is based on the [[https://community.greenbone.net/c/gse][Greenbone Source
Edition (GSE)]] open source project.
** Docker
The source code of [[https://hub.docker.com/u/admirito][admirito]]'s unofficial docker images for Greenbone
Vulnerability Management 11--which is based on [[https://launchpad.net/~mrazavi/+archive/ubuntu/gvm][admirito's GVM PPA]]--is
hosted on this repo. It contains the source for the following docker
images:
- [[https://hub.docker.com/r/admirito/gvmd][gvmd]]: Greenbone Vulnerability Manager
- [[https://hub.docker.com/r/admirito/openvas][openvas]]: OpenVAS remote network security scanner
- [[https://hub.docker.com/r/admirito/gsad][gsad]]: Greenbone Security Assistant
- [[https://hub.docker.com/r/admirito/gvm-postgres][gvm-postgres]]: PostgreSQL 12 Dataabase with libgvm-pg-server
  extension to be used by gvmd
To setup the GVM system with =docker-compose=, just clone the repo and
issue =docker-compose up= command:

#+NAME: setup GVM with docker-compose
#+BEGIN_SRC shell
git clone https://github.com/admirito/gvm-containers.git

cd gvm-containers

docker-compose -f docker-compose.yml -f nvt-sync.yml -f cert-sync.yml -f scap-sync.yml up
#+END_SRC

You can add/remove the =-f ...-sync.yml= arguments from the
=docker-compose= command to enable/disable synchronize NVT/CERT/SCAP
data.

The Greenbone Security Assistant =gsad= port is exposed on the
host's port 8080. So you can access it from [[http://localhost:8080]].

** Helm Chart
A helm chart for deploying the docker images on kubernetes is also
available. For more information please read the [[./chart/README.org][chart/README.org]].
