version: '2.1'

volumes:
  gvm-var-lib: {}
  run-gvm: {}

services:
  scap-sync:
    image: admirito/gvmd:21
    volumes:
      - gvm-var-lib:/var/lib/gvm
      - run-gvm:/run/gvm
    command: greenbone-feed-sync --type SCAP
    # environment:
    #   COMMUNITY_SCAP_RSYNC_FEED: "rsync://feed.community.greenbone.net:/scap-data"
