apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gvm.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "gvm.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "gvm.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
