apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gvm.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
    verbs:
      - get
      - list
      - patch
