{{- if (or .Values.syncFeedsAfterInstall .Values.customFeedsServer.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gvm.fullname" . }}-feeds-sync
  labels:
  {{- include "gvm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "gvm.instance" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ tpl .Values.image.gvmd.registry . }}/{{ tpl .Values.image.gvmd.repository . }}:{{ tpl .Values.image.gvmd.tag . }}"
          imagePullPolicy: {{ tpl .Values.image.gvmd.pullPolicy . }}
          command: ["/bin/sh"]
          args:
            - "-cex"
            - |
              {{- include "gvm.feedSyncShellCommands" . | nindent 14 }}
          {{- if (include "gvm.feedEnvList" .) }}
          env:
            {{- include "gvm.feedEnvList" . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: run-dir
              mountPath: /run
            - name: run-dir
              subPath: gvm
              mountPath: /run/gvm
            - name: data-volume
              subPath: {{ include "gvm.dataSubPathPrefix" . }}openvas
              mountPath: /var/lib/openvas
            - name: data-volume
              subPath: {{ include "gvm.dataSubPathPrefix" . }}gvm
              mountPath: /var/lib/gvm
      volumes:
        - name: run-dir
          emptyDir: {}
        - name: data-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim . | default (include "gvm.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
